# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Irish spellchecker"
ga = "Gaeilge spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Irish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ga = "TRANSLATE: A spellchecker for Irish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ga"

[windows]
system_product_code = "{F7B2E2B4-F029-41C6-80D1-45348F7B559B}_is1"
legacy_product_codes = [
    { value = "D69B037F-205C-4278-91C0-A485C8DC9411", kind = "nsis" },
    { value = "7680D9A9-8F63-4BC8-86A0-DC2A6653BB8B", kind = "nsis" }
]

[package.speller]
name = "Irish"
version = "0.1.1"

[package.grammar]
name = "Irish"
version = "0.1.0"

[package.tts-text-proc]
name = "Irish"
version = "0.1.0"
