template = "https://github.com/giellalt/template-lang-und"
rev_id = 257
template_sha = "0b3fb3d8836831dedcfe3f4b9fcdc3e2aef12fa5"

[replacements]
__GLOTTOLOG_ID__ = "iris1253"
__REPO__ = "lang-gle"
__UND2C__ = "ga"
__UNDEFINED__ = "Irish"
__UND__ = "gle"
