template = "https://github.com/giellalt/template-lang-und"
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "iris1253"
__REPO__ = "lang-gle"
__UND2C__ = "ga"
__UNDEFINED__ = "Irish"
__UND__ = "gle"
